/**
 * @file    hsm_crypto.c
 * @brief   Crypto init + known-answer self-test.
 *
 * KAT vectors in selftest_vectors.h are generated by tools/gen_vectors.c using
 * libsodium, the same library the host uses — so a passing self-test proves the
 * STM32 hardware (AES/HASH) and Monocypher (X25519) agree with the host stack.
 */
#include "hsm_crypto.h"
#include "hsm_hash.h"
#include "hsm_aead.h"
#include "hsm_x25519.h"
#include "stm32u5xx_hal.h"
#include "selftest_vectors.h"

#include <string.h>

/* Word-aligned scratch so the AES/HASH HAL can read buffers as 32-bit words. */
static __attribute__((aligned(4))) uint8_t scratch_a[128];
static __attribute__((aligned(4))) uint8_t scratch_b[128];
static __attribute__((aligned(4))) uint8_t scratch_c[128];

void HSM_Crypto_Init(void)
{
    __HAL_RCC_AES_CLK_ENABLE();
    __HAL_RCC_HASH_CLK_ENABLE();
}

static int eq(const uint8_t *a, const uint8_t *b, size_t n)
{
    return memcmp(a, b, n) == 0 ? 0 : 1;
}

static int test_sha256(void)
{
    memcpy(scratch_a, kat_sha256_in, sizeof(kat_sha256_in));
    if (HSM_Sha256(scratch_a, sizeof(kat_sha256_in), scratch_b) != 0) return 1;
    return eq(scratch_b, kat_sha256_out, sizeof(kat_sha256_out));
}

static int test_hmac(void)
{
    memcpy(scratch_a, kat_hmac_key, sizeof(kat_hmac_key));
    memcpy(scratch_b, kat_hmac_in, sizeof(kat_hmac_in));
    if (HSM_HmacSha256(scratch_a, sizeof(kat_hmac_key),
                       scratch_b, sizeof(kat_hmac_in), scratch_c) != 0) return 1;
    return eq(scratch_c, kat_hmac_out, sizeof(kat_hmac_out));
}

static int test_hkdf(void)
{
    uint8_t okm[sizeof(kat_hkdf_okm)];
    if (HSM_HkdfSha256(kat_hkdf_salt, sizeof(kat_hkdf_salt),
                       kat_hkdf_ikm, sizeof(kat_hkdf_ikm),
                       kat_hkdf_info, sizeof(kat_hkdf_info),
                       okm, sizeof(okm)) != 0) return 1;
    return eq(okm, kat_hkdf_okm, sizeof(okm));
}

/* AES-GCM scratch layout (all word-aligned). Buffers sized generously; the
 * actual lengths come from the vectors so they track gen_vectors.c exactly. */
#define GCM_AAD_LEN sizeof(kat_gcm_aad)
#define GCM_PT_LEN  sizeof(kat_gcm_pt)
static __attribute__((aligned(4))) uint8_t g_key[32];
static __attribute__((aligned(4))) uint8_t g_nonce[12];
static __attribute__((aligned(4))) uint8_t g_aad[64];
static __attribute__((aligned(4))) uint8_t g_buf[128];
static __attribute__((aligned(4))) uint8_t g_out[128];
static __attribute__((aligned(4))) uint8_t g_tag[16];

static void load_gcm(void)
{
    memcpy(g_key, kat_gcm_key, sizeof(g_key));
    memcpy(g_nonce, kat_gcm_nonce, sizeof(g_nonce));
    memcpy(g_aad, kat_gcm_aad, GCM_AAD_LEN);
}

static int test_aesgcm_enc(void)
{
    load_gcm();
    memcpy(g_buf, kat_gcm_pt, GCM_PT_LEN);
    if (HSM_AesGcmEncrypt(g_key, g_nonce, g_aad, GCM_AAD_LEN,
                          g_buf, GCM_PT_LEN, g_out, g_tag) != 0) return 1;
    if (eq(g_out, kat_gcm_ct, sizeof(kat_gcm_ct))) return 1;
    return eq(g_tag, kat_gcm_tag, sizeof(kat_gcm_tag));
}

static int test_aesgcm_dec(void)
{
    load_gcm();
    memcpy(g_buf, kat_gcm_ct, sizeof(kat_gcm_ct));
    memcpy(g_tag, kat_gcm_tag, sizeof(g_tag));
    if (HSM_AesGcmDecrypt(g_key, g_nonce, g_aad, GCM_AAD_LEN,
                          g_buf, GCM_PT_LEN, g_tag, g_out) != 0) return 1;
    return eq(g_out, kat_gcm_pt, sizeof(kat_gcm_pt));
}

static int test_x25519_shared(void)
{
    uint8_t shared[32];
    if (HSM_X25519_Shared(shared, kat_x25519_a, kat_x25519_pub_b) != 0) return 1;
    return eq(shared, kat_x25519_shared, sizeof(shared));
}

static int test_x25519_pub(void)
{
    uint8_t pub[32];
    HSM_X25519_PublicKey(pub, kat_x25519_a);
    return eq(pub, kat_x25519_pub_a, sizeof(pub));
}

int HSM_Crypto_SelfTest(hsm_selftest_t *out)
{
    out->sha256     = (uint8_t)test_sha256();
    out->hmac       = (uint8_t)test_hmac();
    out->hkdf       = (uint8_t)test_hkdf();
    out->aesgcm_enc = (uint8_t)test_aesgcm_enc();
    out->aesgcm_dec = (uint8_t)test_aesgcm_dec();
    out->x25519     = (uint8_t)test_x25519_shared();
    out->x25519_pub = (uint8_t)test_x25519_pub();
    out->overall = (uint8_t)(out->sha256 | out->hmac | out->hkdf |
                             out->aesgcm_enc | out->aesgcm_dec |
                             out->x25519 | out->x25519_pub);
    return out->overall == 0 ? 0 : -1;
}
