/**
 * @file    hsm_crypto.c
 * @brief   Crypto init + known-answer self-test.
 *
 * KAT vectors in selftest_vectors.h are generated by tools/gen_vectors.c using
 * libsodium, the same library the host uses — so a passing self-test proves the
 * STM32 hardware (AES/HASH) and Monocypher (X25519) agree with the host stack.
 */
#include "hsm_crypto.h"
#include "hsm_hash.h"
#include "hsm_aead.h"
#include "hsm_x25519.h"
#include "hsm_ecdsa_p256.h"
#include "stm32u5xx_hal.h"
#include "selftest_vectors.h"

#include <string.h>

/* Word-aligned scratch so the AES/HASH HAL can read buffers as 32-bit words. */
static __attribute__((aligned(4))) uint8_t scratch_a[128];
static __attribute__((aligned(4))) uint8_t scratch_b[128];
static __attribute__((aligned(4))) uint8_t scratch_c[128];

void HSM_Crypto_Init(void)
{
    __HAL_RCC_AES_CLK_ENABLE();
    __HAL_RCC_HASH_CLK_ENABLE();
}

static int eq(const uint8_t *a, const uint8_t *b, size_t n)
{
    return memcmp(a, b, n) == 0 ? 0 : 1;
}

static int test_sha256(void)
{
    memcpy(scratch_a, kat_sha256_in, sizeof(kat_sha256_in));
    if (HSM_Sha256(scratch_a, sizeof(kat_sha256_in), scratch_b) != 0) return 1;
    return eq(scratch_b, kat_sha256_out, sizeof(kat_sha256_out));
}

static int test_hmac(void)
{
    memcpy(scratch_a, kat_hmac_key, sizeof(kat_hmac_key));
    memcpy(scratch_b, kat_hmac_in, sizeof(kat_hmac_in));
    if (HSM_HmacSha256(scratch_a, sizeof(kat_hmac_key),
                       scratch_b, sizeof(kat_hmac_in), scratch_c) != 0) return 1;
    return eq(scratch_c, kat_hmac_out, sizeof(kat_hmac_out));
}

static int test_hkdf(void)
{
    uint8_t okm[sizeof(kat_hkdf_okm)];
    if (HSM_HkdfSha256(kat_hkdf_salt, sizeof(kat_hkdf_salt),
                       kat_hkdf_ikm, sizeof(kat_hkdf_ikm),
                       kat_hkdf_info, sizeof(kat_hkdf_info),
                       okm, sizeof(okm)) != 0) return 1;
    return eq(okm, kat_hkdf_okm, sizeof(okm));
}

/* AES-GCM scratch layout (all word-aligned). Buffers sized generously; the
 * actual lengths come from the vectors so they track gen_vectors.c exactly. */
#define GCM_AAD_LEN sizeof(kat_gcm_aad)
#define GCM_PT_LEN  sizeof(kat_gcm_pt)
static __attribute__((aligned(4))) uint8_t g_key[32];
static __attribute__((aligned(4))) uint8_t g_nonce[12];
static __attribute__((aligned(4))) uint8_t g_aad[64];
static __attribute__((aligned(4))) uint8_t g_buf[128];
static __attribute__((aligned(4))) uint8_t g_out[128];
static __attribute__((aligned(4))) uint8_t g_tag[16];

static void load_gcm(void)
{
    memcpy(g_key, kat_gcm_key, sizeof(g_key));
    memcpy(g_nonce, kat_gcm_nonce, sizeof(g_nonce));
    memcpy(g_aad, kat_gcm_aad, GCM_AAD_LEN);
}

static int test_aesgcm_enc(void)
{
    load_gcm();
    memcpy(g_buf, kat_gcm_pt, GCM_PT_LEN);
    if (HSM_AesGcmEncrypt(g_key, g_nonce, g_aad, GCM_AAD_LEN,
                          g_buf, GCM_PT_LEN, g_out, g_tag) != 0) return 1;
    if (eq(g_out, kat_gcm_ct, sizeof(kat_gcm_ct))) return 1;
    return eq(g_tag, kat_gcm_tag, sizeof(kat_gcm_tag));
}

static int test_aesgcm_dec(void)
{
    load_gcm();
    memcpy(g_buf, kat_gcm_ct, sizeof(kat_gcm_ct));
    memcpy(g_tag, kat_gcm_tag, sizeof(g_tag));
    if (HSM_AesGcmDecrypt(g_key, g_nonce, g_aad, GCM_AAD_LEN,
                          g_buf, GCM_PT_LEN, g_tag, g_out) != 0) return 1;
    return eq(g_out, kat_gcm_pt, sizeof(kat_gcm_pt));
}

static int test_x25519_shared(void)
{
    uint8_t shared[32];
    if (HSM_X25519_Shared(shared, kat_x25519_a, kat_x25519_pub_b) != 0) return 1;
    return eq(shared, kat_x25519_shared, sizeof(shared));
}

static int test_x25519_pub(void)
{
    uint8_t pub[32];
    HSM_X25519_PublicKey(pub, kat_x25519_a);
    return eq(pub, kat_x25519_pub_a, sizeof(pub));
}

/* NIST P-256 example keypair (RFC 6979 A.2.5): private scalar d -> public X,Y.
 * The pubkey derivation is deterministic, so it's a true known-answer test of
 * the PKA path; we then sign + verify a fixed digest to exercise sign/verify. */
static const uint8_t kat_ec_d[32] = {
    0xc9,0xaf,0xa9,0xd8,0x45,0xba,0x75,0x16,0x6b,0x5c,0x21,0x57,0x67,0xb1,0xd6,0x93,
    0x4e,0x50,0xc3,0xdb,0x36,0xe8,0x9b,0x12,0x7b,0x8a,0x62,0x2b,0x12,0x0f,0x67,0x21 };
static const uint8_t kat_ec_qx[32] = {
    0x60,0xfe,0xd4,0xba,0x25,0x5a,0x9d,0x31,0xc9,0x61,0xeb,0x74,0xc6,0x35,0x6d,0x68,
    0xc0,0x49,0xb8,0x92,0x3b,0x61,0xfa,0x6c,0xe6,0x69,0x62,0x2e,0x60,0xf2,0x9f,0xb6 };
static const uint8_t kat_ec_qy[32] = {
    0x79,0x03,0xfe,0x10,0x08,0xb8,0xbc,0x99,0xa4,0x1a,0xe9,0xe9,0x56,0x28,0xbc,0x64,
    0xf2,0xf1,0xb2,0x0c,0x2d,0x7e,0x9f,0x51,0x77,0xa3,0xc2,0x94,0xd4,0x46,0x22,0x99 };

static int test_ecdsa_p256(void)
{
    uint8_t pub[64];
    if (HSM_EcdsaP256_Public(kat_ec_d, pub) != 0) return 1;
    if (eq(pub, kat_ec_qx, 32) || eq(pub + 32, kat_ec_qy, 32)) return 1;  /* deterministic KAT */

    uint8_t digest[32];
    for (int i = 0; i < 32; i++) digest[i] = (uint8_t)(0xA0 + i);
    uint8_t sig[64];
    if (HSM_EcdsaP256_Sign(kat_ec_d, digest, sig) != 0) return 1;
    return HSM_EcdsaP256_Verify(pub, digest, sig) == 0 ? 0 : 1;          /* sign->verify */
}

int HSM_Crypto_SelfTest(hsm_selftest_t *out)
{
    out->sha256     = (uint8_t)test_sha256();
    out->hmac       = (uint8_t)test_hmac();
    out->hkdf       = (uint8_t)test_hkdf();
    out->aesgcm_enc = (uint8_t)test_aesgcm_enc();
    out->aesgcm_dec = (uint8_t)test_aesgcm_dec();
    out->x25519     = (uint8_t)test_x25519_shared();
    out->x25519_pub = (uint8_t)test_x25519_pub();
    out->ecdsa_p256 = (uint8_t)test_ecdsa_p256();
    out->overall = (uint8_t)(out->sha256 | out->hmac | out->hkdf |
                             out->aesgcm_enc | out->aesgcm_dec |
                             out->x25519 | out->x25519_pub | out->ecdsa_p256);
    return out->overall == 0 ? 0 : -1;
}
