/* Generates known-answer-test vectors for the firmware crypto self-test,
 * using libsodium as ground truth. Emits a C header on stdout. */
#include <sodium.h>
#include <stdio.h>
#include <string.h>

static void emit(const char *name, const unsigned char *p, size_t n)
{
    printf("static const uint8_t %s[%zu] = {", name, n);
    for (size_t i = 0; i < n; i++) {
        if (i % 12 == 0) printf("\n    ");
        printf("0x%02x,%s", p[i], (i % 12 == 11) ? "" : " ");
    }
    printf("\n};\n\n");
}

int main(void)
{
    if (sodium_init() < 0) return 1;
    if (!crypto_aead_aes256gcm_is_available()) {
        fprintf(stderr, "AES-256-GCM not available on this host\n");
        return 1;
    }

    printf("/* AUTO-GENERATED by tools/gen_vectors.c (libsodium). Do not edit. */\n");
    printf("#ifndef OPENHSM_SELFTEST_VECTORS_H\n#define OPENHSM_SELFTEST_VECTORS_H\n");
    printf("#include <stdint.h>\n\n");

    /* ---- SHA-256 ---- */
    const char *sha_in = "OpenHSM-SelfTest";
    unsigned char sha_out[32];
    crypto_hash_sha256(sha_out, (const unsigned char *)sha_in, strlen(sha_in));
    emit("kat_sha256_in", (const unsigned char *)sha_in, strlen(sha_in));
    emit("kat_sha256_out", sha_out, sizeof(sha_out));

    /* ---- HMAC-SHA256 (arbitrary-length key) ---- */
    unsigned char hk[32];
    memset(hk, 0x0b, sizeof(hk));
    const char *hd = "Hi There";
    unsigned char hmac_out[32];
    crypto_auth_hmacsha256_state st;
    crypto_auth_hmacsha256_init(&st, hk, sizeof(hk));
    crypto_auth_hmacsha256_update(&st, (const unsigned char *)hd, strlen(hd));
    crypto_auth_hmacsha256_final(&st, hmac_out);
    emit("kat_hmac_key", hk, sizeof(hk));
    emit("kat_hmac_in", (const unsigned char *)hd, strlen(hd));
    emit("kat_hmac_out", hmac_out, sizeof(hmac_out));

    /* ---- HKDF-SHA256 (RFC 5869) ---- mirrors the real session KDF:
     * 64-byte salt (= nonce_h||nonce_d, exactly the SHA-256 block size) and the
     * session info string, to exercise the HW HMAC block-sized-key path. */
    unsigned char ikm[32]; memset(ikm, 0x0b, sizeof(ikm));
    unsigned char salt[64]; for (int i = 0; i < 64; i++) salt[i] = (unsigned char)i;
    const char *info = "OpenHSM/v1 session keys";
    unsigned char prk[crypto_kdf_hkdf_sha256_KEYBYTES];
    crypto_kdf_hkdf_sha256_extract(prk, salt, sizeof(salt), ikm, sizeof(ikm));
    unsigned char okm[64];
    crypto_kdf_hkdf_sha256_expand(okm, sizeof(okm), info, strlen(info), prk);
    emit("kat_hkdf_ikm", ikm, sizeof(ikm));
    emit("kat_hkdf_salt", salt, sizeof(salt));
    emit("kat_hkdf_info", (const unsigned char *)info, strlen(info));
    emit("kat_hkdf_okm", okm, sizeof(okm));

    /* ---- AES-256-GCM (session-shaped: AAD=16 exact block, PT=18) ---- */
    unsigned char gkey[32]; for (int i = 0; i < 32; i++) gkey[i] = (unsigned char)(0x40 + i);
    unsigned char gnonce[12]; for (int i = 0; i < 12; i++) gnonce[i] = (unsigned char)(0xA0 + i);
    unsigned char gaad[16]; for (int i = 0; i < 16; i++) gaad[i] = (unsigned char)(0x10 + i);
    unsigned char gpt[18]; for (int i = 0; i < 18; i++) gpt[i] = (unsigned char)i;
    unsigned char gct[18]; unsigned char gtag[16]; unsigned long long maclen = 0;
    crypto_aead_aes256gcm_encrypt_detached(gct, gtag, &maclen,
        gpt, sizeof(gpt), gaad, sizeof(gaad), NULL, gnonce, gkey);
    emit("kat_gcm_key", gkey, sizeof(gkey));
    emit("kat_gcm_nonce", gnonce, sizeof(gnonce));
    emit("kat_gcm_aad", gaad, sizeof(gaad));
    emit("kat_gcm_pt", gpt, sizeof(gpt));
    emit("kat_gcm_ct", gct, sizeof(gct));
    emit("kat_gcm_tag", gtag, sizeof(gtag));

    /* ---- X25519 (RFC 7748 style) ---- */
    unsigned char a[32]; for (int i = 0; i < 32; i++) a[i] = (unsigned char)(0x70 + i);
    unsigned char b[32]; for (int i = 0; i < 32; i++) b[i] = (unsigned char)(0x90 + i);
    unsigned char pub_a[32], pub_b[32], shared[32];
    crypto_scalarmult_curve25519_base(pub_a, a);
    crypto_scalarmult_curve25519_base(pub_b, b);
    crypto_scalarmult_curve25519(shared, a, pub_b);
    emit("kat_x25519_a", a, sizeof(a));
    emit("kat_x25519_pub_a", pub_a, sizeof(pub_a));
    emit("kat_x25519_pub_b", pub_b, sizeof(pub_b));
    emit("kat_x25519_shared", shared, sizeof(shared));

    printf("#endif /* OPENHSM_SELFTEST_VECTORS_H */\n");
    return 0;
}
