/*
 * sign_image — OpenHSM secure-boot signing tool (host, libsodium).
 *
 *   sign_image keygen <seed.out> <vendor_pubkey.h.out>
 *       Generate a vendor Ed25519 signing key: writes the 32-byte seed and a
 *       C header with the public key for the bootloader to bake in.
 *
 *   sign_image sign <bootloader.bin> <app.bin> <seed> <version> <out.bin>
 *       Produce a combined, signed, flashable image:
 *         [0x00000] bootloader (<= 64 KB)
 *         [0x10000] img_header { magic, version, img_len, reserved, sig[64] }
 *         [0x12000] application
 *       Signature = Ed25519 over  u32le(version) || u32le(img_len) || app[].
 *
 * libsodium's crypto_sign_* is RFC 8032 Ed25519, verifiable by Monocypher's
 * crypto_ed25519_check on the device.
 *
 * Build (host):  cc tools/sign_image.c -lsodium -o tools/sign_image
 */
#include "../bootloader/image_header.h"

#include <sodium.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

static long read_file(const char *path, uint8_t **out, long max)
{
    FILE *f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "open %s: ", path); perror(""); return -1; }
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (n < 0 || (max > 0 && n > max)) { fprintf(stderr, "%s: bad size %ld (max %ld)\n", path, n, max); fclose(f); return -1; }
    uint8_t *buf = malloc((size_t)(n ? n : 1));
    if (fread(buf, 1, (size_t)n, f) != (size_t)n) { fclose(f); free(buf); return -1; }
    fclose(f);
    *out = buf;
    return n;
}

static int write_file(const char *path, const uint8_t *buf, size_t n)
{
    FILE *f = fopen(path, "wb");
    if (!f) { fprintf(stderr, "create %s: ", path); perror(""); return -1; }
    int ok = fwrite(buf, 1, n, f) == n;
    fclose(f);
    return ok ? 0 : -1;
}

static void put_u32le(uint8_t *p, uint32_t v)
{
    p[0] = (uint8_t)v; p[1] = (uint8_t)(v >> 8); p[2] = (uint8_t)(v >> 16); p[3] = (uint8_t)(v >> 24);
}

static int do_keygen(const char *seed_path, const char *hdr_path)
{
    uint8_t seed[crypto_sign_SEEDBYTES];           /* 32 */
    uint8_t pk[crypto_sign_PUBLICKEYBYTES];        /* 32 */
    uint8_t sk[crypto_sign_SECRETKEYBYTES];        /* 64 */
    randombytes_buf(seed, sizeof(seed));
    crypto_sign_seed_keypair(pk, sk, seed);

    if (write_file(seed_path, seed, sizeof(seed)) != 0) return 1;

    FILE *h = fopen(hdr_path, "w");
    if (!h) { perror("create header"); return 1; }
    fprintf(h, "/* AUTO-GENERATED by tools/sign_image.c keygen. Do not edit. */\n");
    fprintf(h, "#ifndef OPENHSM_VENDOR_PUBKEY_H\n#define OPENHSM_VENDOR_PUBKEY_H\n#include <stdint.h>\n");
    fprintf(h, "static const uint8_t openhsm_vendor_pubkey[32] = {\n   ");
    for (int i = 0; i < 32; i++) fprintf(h, " 0x%02x,", pk[i]);
    fprintf(h, "\n};\n#endif\n");
    fclose(h);

    sodium_memzero(seed, sizeof(seed));
    sodium_memzero(sk, sizeof(sk));
    fprintf(stderr, "keygen: wrote %s (seed) and %s (public key)\n", seed_path, hdr_path);
    return 0;
}

static int do_sign(const char *bl_path, const char *app_path, const char *seed_path,
                   uint32_t version, const char *out_path)
{
    uint8_t *bl = NULL, *app = NULL, *seed = NULL;
    long bl_len  = read_file(bl_path, &bl, BOOT_BL_SIZE);
    long app_len = read_file(app_path, &app, BOOT_APP_MAX_LEN);
    long seed_len = read_file(seed_path, &seed, crypto_sign_SEEDBYTES);
    if (bl_len < 0 || app_len < 0 || seed_len != crypto_sign_SEEDBYTES) return 1;

    uint8_t pk[crypto_sign_PUBLICKEYBYTES], sk[crypto_sign_SECRETKEYBYTES];
    crypto_sign_seed_keypair(pk, sk, seed);

    /* Signed message: u32le(version) || u32le(img_len) || app[]. */
    size_t msg_len = 8 + (size_t)app_len;
    uint8_t *msg = malloc(msg_len);
    put_u32le(msg, version);
    put_u32le(msg + 4, (uint32_t)app_len);
    memcpy(msg + 8, app, (size_t)app_len);

    uint8_t sig[crypto_sign_BYTES];                /* 64 */
    crypto_sign_detached(sig, NULL, msg, msg_len, sk);

    /* Assemble the 0xFF-padded combined image. */
    size_t total = (BOOT_APP_ADDR - BOOT_BL_BASE) + (size_t)app_len;  /* 0x12000 + app */
    uint8_t *img = malloc(total);
    memset(img, 0xFF, total);
    memcpy(img + 0, bl, (size_t)bl_len);

    img_header_t hdr;
    memset(&hdr, 0xFF, sizeof(hdr));
    hdr.magic = IMG_MAGIC;
    hdr.version = version;
    hdr.img_len = (uint32_t)app_len;
    hdr.reserved = 0;
    memcpy(hdr.sig, sig, 64);
    memcpy(img + (BOOT_HEADER_ADDR - BOOT_BL_BASE), &hdr, sizeof(hdr));

    memcpy(img + (BOOT_APP_ADDR - BOOT_BL_BASE), app, (size_t)app_len);

    int rc = write_file(out_path, img, total);
    if (rc == 0)
        fprintf(stderr, "sign: %s  bl=%ld app=%ld version=%u total=%zu bytes\n",
                out_path, bl_len, app_len, version, total);

    sodium_memzero(sk, sizeof(sk));
    free(bl); free(app); free(seed); free(msg); free(img);
    return rc ? 1 : 0;
}

int main(int argc, char **argv)
{
    if (sodium_init() < 0) { fprintf(stderr, "libsodium init failed\n"); return 1; }
    if (argc >= 4 && !strcmp(argv[1], "keygen"))
        return do_keygen(argv[2], argv[3]);
    if (argc == 7 && !strcmp(argv[1], "sign"))
        return do_sign(argv[2], argv[3], argv[4], (uint32_t)strtoul(argv[5], NULL, 0), argv[6]);

    fprintf(stderr,
        "usage:\n"
        "  %s keygen <seed.out> <vendor_pubkey.h.out>\n"
        "  %s sign <bootloader.bin> <app.bin> <seed> <version> <out.bin>\n",
        argv[0], argv[0]);
    return 2;
}
